services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parallel-hearts-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
